version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: renepardon/docker-for-artisans
    links:
      - db
      - redis
      - maildev
    ports:
      - "8082:80"
    restart: always
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  db:
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes: []
      # - "mysql-data:/var/lib/mysql"
      # - /my/own/datadir:/var/lib/mysql
    image: mariadb

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    restart: always

  redis:
    image: redis
    expose:
      - 6379
    restart: always

  # it's a combination of queue worker and cronjob execution
  worker:
    build:
      context: .
      dockerfile: Dockerfile.cron.dev
    command: php artisan queue:work redis --tries=3 --sleep=5
    image: renepardon/docker-for-artisans-worker
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

volumes:
  mysql-data:
